server:
  port: 8081

swagger:
  enabled: true

spring:
  #数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
    url: jdbc:mysql://121.36.9.198:3306/local?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false

#mybatis-plus:
#  mapper-locations: classpath:mapper/*Mapper.xml
