server:
  port: 8081

swagger:
  enabled: true

#spring:
#  #数据源
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: db@sps@dk_0618!
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 2
#    url: jdbc:mysql://115.231.102.138:9306/parking_garage?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
#
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    #返回Map类型时字段不现实问题
#    call-setters-on-nulls: true
